### ISSUE TITLE
Fatal error when deploying production: LoadError: cannot load such file -- rubocop/rake_task

### ISSUE THREAD

**Issue by kaydanzie** [chapmanu/imposter#4]
When trying to run `cap production deploy` for PR #3 I got an error on the step `deploy:assets:precompile`. It's trying to run `rake test` when it shouldn't.

Error:
```
01 /usr/local/rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 rake aborted!
      01 LoadError: cannot load such file -- rubocop/rake_task
      01 /var/www/imposter/releases/20170825174722/lib/tasks/test.rake:1:in `require'
      01 /var/www/imposter/releases/20170825174722/lib/tasks/test.rake:1:in `<top (required)>'
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:648:in `load'
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:648:in `block in r…
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:648:in `each'
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:648:in `run_tasks_…
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/application.rb:440:in `run_t…
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/railties-5.1.3/lib/rails/engine.rb:457:in `load_tasks'
      01 /var/www/imposter/releases/20170825174722/Rakefile:6:in `<top (required)>'
      01 /var/www/imposter/shared/bundle/ruby/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
      01 /usr/local/rbenv/versions/2.4.0/bin/bundle:22:in `load'
      01 /usr/local/rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
      01 (See full trace by running task with --trace)
```

**Comment by tatwell** [comment]
The configuration looks identical to Cascade Assets where we are not hitting this error. I wonder if Rails 5 changed the way it loads libraries so that it now preloads all [lib/tasks](https://github.com/chapmanu/imposter/tree/development/lib/tasks) files.

If it were to do something like this, it would explain why it executes `require 'rubocop/rake_task'` in this case causing the error and not in Cascade Assets.

**Comment by tatwell** [comment]
Try moving the `require` statement under the task block as suggested [here](https://github.com/interagent/pliny/issues/296#issuecomment-270994923):

```
# Add additional test suite definitions to the default test task here
namespace :test do
  desc 'Runs RuboCop on specified directories'
  RuboCop::RakeTask.new(:rubocop) do |task|
    require 'rubocop/rake_task'
```

**Comment by tatwell** [comment]
I think the explanation is in here somewhere:

- https://stackoverflow.com/a/40019108/6763239

**Comment by kaydanzie** [comment]
After a little research, I haven't come across any good workarounds. It's hard to find anyone reporting a similar issue from what I can tell. I am not familiar with capistrano at all or configuring deployment.

The temporary resolution at this point is just to remove the `group :test` from the Gemfile for rubocop.

**Comment by tatwell** [comment]
That works for me for now. Leave this issue open and I expect an answer will turn up eventually.

**Comment by kaydanzie** [comment]
Came across this again in Newsroom, which is also running Rails 5. I resolved it by following the recommendation in this issue to move the `rubocop` gem outside the test group in the Gemfile. There isn't anything in the Rubocop documentation or issues that offers a good recommendation on how to handle. Since it's not really a big deal to require the gem in all environments, we're just going to leave it there for now and close this issue.

**Comment by diasjorge** [comment]
For anyone that ends up here I found this an acceptable solution.

```
begin
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new do |t|
    t.options = ['--display-cop-names']
  end
rescue LoadError
end
```
